embedding_models:
  - name: Qwen/Qwen3-Embedding-0.6B
    dimension: 1024
    api_key:
    api_base:
    type: huggingface # openai
    device: cuda

enable_reranking: true
reranking:
  top_k: 4
  type: qwen_cross_encoder # Options: flag_reranker, cross_encoder, qwen_cross_encoder
  name: tomaarsen/Qwen3-Reranker-0.6B-seq-cls # Options: BAAI/bge-reranker-v2-m3, jinaai/jina-reranker-v2-base-multilingual, tomaarsen/Qwen3-Reranker-0.6B-seq-cls

vector_store:
  type: qdrant
  host: localhost
  port: 6333
  api_key:
  use_async: true
  chunk_size: 100
  chunk_overlap: 50
  on_disk: True

batch_size: 1
default_score_threshold: 0.0
